#!/bin/bash
# Writes your signing details into project.yml and regenerates the project.
#
# WHY A SCRIPT: the project is generated by XcodeGen, so anything you set in
# Xcode's Signing & Capabilities pane is wiped the next time the project is
# regenerated. Signing has to live in project.yml to survive.
#
#   tools/setup-device-signing.sh <TEAM_ID> [BUNDLE_ID]
#
# TEAM_ID is the 10-character team identifier. Find it in Xcode:
#   Settings → Accounts → select your Apple ID → the ID column next to the team.
# A free Apple ID works: it gives a "Personal Team" whose builds run on your own
# device for 7 days before they need re-installing. That is enough for testing.
#
# BUNDLE_ID defaults to com.<your team id lowercased>.coachme, because the stock
# com.coachme.app is very likely already registered by someone else and a free
# Personal Team cannot claim a taken identifier.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ $# -lt 1 ]; then
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 1
fi

TEAM="$1"
BUNDLE="${2:-com.$(echo "$TEAM" | tr '[:upper:]' '[:lower:]').coachme}"

# Refuse placeholder text outright. Pasting the usage line verbatim writes an
# unusable team and a bundle identifier containing non-ASCII characters, which
# then fails much later with an error that says nothing about the real cause.
if ! [[ "$TEAM" =~ ^[A-Za-z0-9]{10}$ ]]; then
  echo "错误：'$TEAM' 不是有效的 Team ID。" >&2
  echo "" >&2
  echo "Team ID 是 10 位字母数字，例如 A1B2C3D4E5。去这里找：" >&2
  echo "  Xcode → Settings → Accounts → 选中你的 Apple ID → 右侧团队列表的 TEAM ID 一列" >&2
  echo "" >&2
  echo "如果那里是空的，说明还没登录 Apple ID，先点左下角 + 添加。" >&2
  exit 1
fi

python3 - "$TEAM" "$BUNDLE" <<'PY'
import re, sys, pathlib
team, bundle = sys.argv[1], sys.argv[2]
p = pathlib.Path("project.yml")
s = p.read_text()
s2 = re.sub(r'(\n\s*DEVELOPMENT_TEAM:).*', r'\g<1> "%s"' % team, s, count=1)
if s2 == s:
    raise SystemExit("project.yml 里没找到 DEVELOPMENT_TEAM，请检查文件")
s3 = re.sub(r'(\n\s*PRODUCT_BUNDLE_IDENTIFIER:).*', r'\g<1> %s' % bundle, s2, count=1)
if s3 == s2:
    raise SystemExit("project.yml 里没找到 PRODUCT_BUNDLE_IDENTIFIER，请检查文件")
p.write_text(s3)
print(f"project.yml 已更新：team={team}  bundle={bundle}")
PY

tools/setup-xcode-project.sh
echo
echo "接下来："
echo "  1. open CoachMe.xcworkspace"
echo "  2. 顶部设备选择器里选你的 iPhone"
echo "  3. ⌘R 运行"
echo "  4. 首次运行后在 iPhone 上：设置 → 通用 → VPN 与设备管理 → 信任你的开发者证书"
